### PR TITLE
Update registry.yml > pyvo

### PR DESCRIPTION
**Pull request by funbaker**
Changed maintainer and description
Image and educational resource will follow soon(tm)

https://github.com/pyvirtobs/pyvo/issues/85

### CODE REVIEW

**Comment by mwcraig** [comment]
Thanks, I'll merge once you have added those too!

**Comment by funbaker** [comment]
Is there some kind of deadline for this?

**Comment by mwcraig** [comment]
I'll hand the blog post off to numfocus this week, but for the registry update, maybe a couple weeks?

**Comment by mwcraig** [comment]
@funbaker -- I'm going to merge this, but feel free to provide more detail when you get a chance.

**Pull request merged**
